
name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/main/main.cpp src/lib/pwgen.cpp src/lib/pwgen.h src/lib/sha1.cpp src/lib/sha1.h && git diff --exit-code

      - name: Build application
        run: make
      
      - name: Run application
        run: ./bin/pwgen
        
      - name: Test application
        run: make test
        
      - name: Run test application
        run: ./bin/test
